apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZWE5oWTJocFpXbG5iM0k2WjJod1h6WlRkRFpHUVdkU1ZtcE1WVGhQV0doeE5GRnZNV2xwYlRWcE9UaDBOekZxU2tsdk9RPT0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson