apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZWE5oWTJocGVXbG5iM0k2WjJod1gybHlURTU2YzBGdWRtdFJNREpVWVhORFJERm1OVVpYUmtWMldtMURSRFEzWVZScmRRPT0ifX19Cg==
type: kubernetes.io/dockerconfigjson
